### ISSUE TITLE
Report issues with the Hybrid Messaging SDK v2.3.3?

### ISSUE THREAD

**Issue by mhelder** [CMTelecom/Hybrid-Messaging#1]
Hi,

Is this the right place for me to raise some issues I encountered while integrating Hybrid Messaging SDK version 2.3.3 in an Android app for a client?

If not, I would appreciate a nudge in the right direction.

Thanks,
Matt

**Comment by joepb** [comment]
Hi Matt,

This is a quite old and unmaintained repo. Tbh I'm surprised to discover it even still exists...
Support for the Hybrid Messaging SDK is very much declining and (though not officially yet) it's very likely to be discontinued soon.

For additional questions, feel free to reach out via https://www.cm.com/contact/support/

Joep

**Comment by mhelder** [comment]
Hi Joep,

I appreciate the quick reply! 

Just for my understanding: when you say that the Hybrid Messaging SDK is on its way out, does that also apply to the [2.0.0 version described in CM's documentation](https://docs.cmtelecom.com/hybrid-messaging/v2.0.0), or did you specifically mean to the 1.x version of the Android SDK?

In other words: are the "Android SDK v2.3.3" (and "iOS SDK v1.3.0") also expected to be discontinued soon?

Thanks.

**Comment by joepb** [comment]
I am referring to the whole Hybrid platform. There is hardly any demand for it anymore, and as such we are looking into alternatives. If you are actively using the hybrid platform, we will inform you well in time, of course.

Joep

**Comment by mhelder** [comment]
Thanks for clearing that up! 👍
